const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../miniprogram/components/daily-composer')
const json = JSON.parse(fs.readFileSync(path.join(root, 'daily-composer.json'), 'utf8'))
const js = fs.readFileSync(path.join(root, 'daily-composer.js'), 'utf8')
const wxml = fs.readFileSync(path.join(root, 'daily-composer.wxml'), 'utf8')
const wxss = fs.readFileSync(path.join(root, 'daily-composer.wxss'), 'utf8')

assert.strictEqual(json.component, true)

assert.match(wxml, /class="composer-shell"/)
assert.match(wxml, /mic-button/)
assert.match(wxml, /camera-button/)
assert.match(wxml, /<textarea/)
assert.match(wxml, /输入今天的饮食或运动记录/)
assert.match(wxml, /submit-button/)
assert.match(wxml, /正在录音/)
assert.match(wxml, /正在转写/)
assert.match(wxml, /voiceDurationText/)
assert.match(wxml, /wave-bar/)
assert.match(wxml, /上滑取消/)
assert.match(wxml, /松开取消/)
assert.match(wxml, /bindtouchcancel="onMicTouchCancel"/)

assert.match(js, /triggerEvent\('input'/)
assert.match(js, /triggerEvent\('submit'/)
assert.match(js, /triggerEvent\('voicestart'/)
assert.match(js, /triggerEvent\('voicestop'/)
assert.match(js, /triggerEvent\('voicecancel'/)
assert.match(js, /onMicTouchCancel/)
assert.match(js, /triggerEvent\('cameratap'/)
assert.match(js, /HOLD_THRESHOLD_MS\s*=\s*350/)
assert.match(js, /CANCEL_DISTANCE_PX\s*=\s*60/)

assert.match(wxss, /border-radius:\s*48rpx/)
assert.match(wxss, /backdrop-filter:\s*blur/)
assert.match(wxss, /\.wave-bar/)
assert.match(wxss, /@keyframes voice-wave/)
assert.match(wxss, /\.composer-button:active/)
