const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const recordScript = fs.readFileSync(path.join(root, 'miniprogram/pages/record/record.js'), 'utf8')
const recordMarkup = fs.readFileSync(path.join(root, 'miniprogram/pages/record/record.wxml'), 'utf8')
const statisticsScript = fs.readFileSync(path.join(root, 'miniprogram/pages/statistics/statistics.js'), 'utf8')
const statisticsMarkup = fs.readFileSync(path.join(root, 'miniprogram/pages/statistics/statistics.wxml'), 'utf8')
const appConfig = JSON.parse(fs.readFileSync(path.join(root, 'miniprogram/app.json'), 'utf8'))

assert.doesNotMatch(recordScript, /STORAGE_KEYS\.records/)
assert.match(recordScript, /action:\s*'range'/)
assert.match(recordScript, /action:\s*'delete'/)
assert.match(recordScript, /wx\.showModal/)
assert.match(recordMarkup, /empty-state/)
assert.match(recordMarkup, /饮食摄入/)
assert.match(recordMarkup, /运动消耗/)

assert.match(statisticsScript, /action:\s*'range'/)
assert.match(statisticsScript, /rangeDays/)
assert.match(statisticsScript, /console\.error\('dailyRecords range returned failure'/)
assert.match(statisticsScript, /errCode/)
assert.match(statisticsScript, /errMsg/)
assert.match(statisticsMarkup, /摄入热量趋势/)
assert.match(statisticsMarkup, /运动消耗趋势/)
assert.match(statisticsMarkup, /净摄入趋势/)
assert.match(statisticsMarkup, /体重趋势/)
assert.match(statisticsMarkup, /empty-state/)
assert.ok(appConfig.pages.includes('pages/statistics/statistics'))
assert.ok(appConfig.tabBar.list.some((item) => item.pagePath === 'pages/statistics/statistics'))

console.log('history and statistics page tests passed')
