const assert = require('assert')
const fs = require('fs')
const path = require('path')

const read = (file) => fs.readFileSync(path.resolve(__dirname, '..', file), 'utf8')

const todayJs = read('miniprogram/pages/today/today.js')
const todayWxml = read('miniprogram/pages/today/today.wxml')
const todayWxss = read('miniprogram/pages/today/today.wxss')
const composerWxml = read('miniprogram/components/daily-composer/daily-composer.wxml')

assert.match(todayJs, /recordError/)
assert.match(todayJs, /retryDailyRecord/)
assert.match(todayJs, /aiError/)
assert.match(todayWxml, /state-view/)
assert.match(todayWxml, /bindtap="retryDailyRecord"/)
assert.match(todayWxml, /智能识别失败/)
assert.match(todayWxml, /goal-ring/)
assert.match(todayWxml, /今日建议/)
assert.match(todayJs, /getDeficitSizeClass/)
assert.match(todayWxml, /calorieDeficitSizeClass/)
assert.match(todayJs, /onInputKeyboardHeightChange/)
assert.match(todayWxml, /bindkeyboardheightchange="onInputKeyboardHeightChange"/)
assert.match(composerWxml, /输入今天的饮食或运动记录\.\.\./)
assert.match(composerWxml, /adjust-position="{{true}}"/)
assert.match(composerWxml, /cursor-spacing="12"/)
assert.doesNotMatch(todayJs, /inputDockStyle/)
assert.doesNotMatch(todayJs, /keyboardHeight\s*\+\s*8/)
assert.doesNotMatch(todayWxml, /style="{{inputDockStyle}}"/)
assert.match(todayWxml, /<view class="today-root">/)
assert.match(todayWxml, /<scroll-view class="page-content today-page" scroll-y/)
assert.ok(todayWxml.indexOf('<view class="input-dock"') > todayWxml.indexOf('</scroll-view>'))
assert.match(todayWxss, /deficit-size-medium/)
assert.match(todayWxss, /--composer-gap:\s*16px/)
assert.match(todayWxss, /\.input-dock\s*\{[\s\S]*?position:\s*fixed;[\s\S]*?right:\s*0;[\s\S]*?left:\s*0;[\s\S]*?z-index:\s*999;/)
assert.match(todayWxss, /\.input-dock\s*\{[\s\S]*?bottom:\s*var\(--composer-gap\);/)
assert.match(todayWxss, /\.recent-foods-panel\s*\{[\s\S]*?margin-bottom:\s*16rpx;/)
assert.match(todayWxss, /\.today-page\s*\{[\s\S]*?padding:[^;]+var\(--composer-reserve\)[^;]+var\(--composer-gap\)/)
const deficitNumberStyle = todayWxss.match(/\.deficit-number\s*\{[^}]+\}/)[0]
assert.doesNotMatch(deficitNumberStyle, /text-overflow:\s*ellipsis/)

const onboarding = read('miniprogram/pages/onboarding/onboarding.wxml')
const profileJs = read('miniprogram/pages/profile/profile.js')
const profileWxml = read('miniprogram/pages/profile/profile.wxml')

assert.match(onboarding, /settings-group/)
assert.match(onboarding, /recommendation-panel/)
assert.match(profileJs, /profileError/)
assert.match(profileJs, /retryCloudProfile/)
assert.match(profileWxml, /settings-group/)
assert.doesNotMatch(profileWxml, /wx:for="{{options}}"/)

const entryJs = read('miniprogram/pages/entry/entry.js')
const entryWxml = read('miniprogram/pages/entry/entry.wxml')
const confirmJs = read('miniprogram/pages/confirm/confirm.js')
const confirmWxml = read('miniprogram/pages/confirm/confirm.wxml')

assert.match(entryJs, /aiError/)
assert.match(entryWxml, /bindtap="parseText"/)
assert.match(entryWxml, /error-banner/)
assert.match(confirmJs, /saveError/)
assert.match(confirmJs, /hasParsedItems/)
assert.match(confirmWxml, /disabled="{{saving \|\| !hasParsedItems}}"/)

const recordJs = read('miniprogram/pages/record/record.js')
const recordWxml = read('miniprogram/pages/record/record.wxml')
const statisticsJs = read('miniprogram/pages/statistics/statistics.js')
const statisticsWxml = read('miniprogram/pages/statistics/statistics.wxml')

assert.match(recordJs, /recordError/)
assert.match(recordJs, /retryRecord/)
assert.match(recordWxml, /bindtap="retryRecord"/)
assert.match(statisticsJs, /statisticsError/)
assert.match(statisticsJs, /requestSequence/)
assert.match(statisticsJs, /retryStatistics/)
assert.match(statisticsWxml, /bindtap="retryStatistics"/)
