const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const todayJs = fs.readFileSync(path.join(root, 'miniprogram/pages/today/today.js'), 'utf8')
const todayWxml = fs.readFileSync(path.join(root, 'miniprogram/pages/today/today.wxml'), 'utf8')
const composerJs = fs.readFileSync(path.join(root, 'miniprogram/components/daily-composer/daily-composer.js'), 'utf8')

assert.match(todayJs, /wx\.showActionSheet\(/)
assert.match(todayJs, /wx\.chooseImage\(/)
assert.match(todayJs, /wx\.compressImage\(/)
assert.match(todayJs, /wx\.cloud\.uploadFile\(/)
assert.match(todayJs, /fileID/)
assert.doesNotMatch(todayJs, /data:\s*\{[\s\S]*imageBase64/)
assert.match(todayJs, /name:\s*['"]recognizeFoodImage['"]/)
assert.match(todayJs, /STORAGE_KEYS\.pendingParse/)
assert.match(todayJs, /pages\/confirm\/confirm/)
assert.match(todayJs, /图片处理失败，请重新选择一张照片/)
assert.match(todayJs, /暂时无法识别这张图片，请重新拍摄或手动记录/)
assert.doesNotMatch(todayJs, /imageBase64/)
assert.doesNotMatch(todayJs, /readImageBase64/)
assert.match(todayWxml, /cameraParsing/)
assert.match(composerJs, /imageParsing/)
